### ISSUE TITLE
phpdocumentor/type-resolver version

### ISSUE THREAD

**Issue by pamil** [digitalkaoz/typehint-to-docblock#3]
Can we use `phpdocumentor/type-resolver` `0.1.4` instead of that `@dev` version? It's the only dev package in requirements.

**Comment by digitalkaoz** [comment]
fixed in `0.2.1`

**Comment by pamil** [comment]
Actually, `0.1.4` requires another dev dependency, `0.1.1` not but introduces bug in partial typehints. I've just made an issue in their repo related to it. I'll use the phar version instead for now :)

**Comment by digitalkaoz** [comment]
using the phar is the recommend way for travis i think

**Comment by digitalkaoz** [comment]
@pamil let me know if the typeresolver has a stable version without dev dependencies
